version: '2'
services:
    hindakogemust-app:
        image: hindakogemust
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hindakogemust-mysql:3306/hindakogemust?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hindakogemust-elasticsearch:9300
        ports:
            - 8080:8080
    hindakogemust-mysql:
        extends:
            file: mysql.yml
            service: hindakogemust-mysql
    hindakogemust-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hindakogemust-elasticsearch
