INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elinda Tragel', 'Lorem Ipsum 1', 9, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Frank Bolyard', 'Labore quaerat etincidunt adipisci labore dolorem.', 5, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Barbara Miller', 'Ut dolore adipisci porro tempora eius aliquam aliquam.', 8, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Frank Mcgee', 'Aliquam quiquia voluptatem dolor quaerat amet.', 3, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Christopher Sanchez', 'Numquam modi consectetur velit non labore adipisci.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janice Shields', 'Numquam adipisci amet dolore.', 3, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lucille Mcrae', 'Porro numquam sed ut voluptatem sed sed amet.', 8, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Walls', 'Eius quaerat magnam dolore est dolor voluptatem.', 10, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ida Decaro', 'Adipisci magnam aliquam porro aliquam.', 4, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Annie Whitting', 'Aliquam eius quiquia neque numquam modi.', 10, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Milton Hsiao', 'Numquam quisquam quaerat velit numquam ipsum etincidunt.', 8, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elizabeth Trout', 'Tempora labore etincidunt amet.', 8, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeffery Blount', 'Sit dolore adipisci labore est.', 10, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Santiago Bladen', 'Quisquam ipsum quiquia sed dolorem tempora.', 1, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sergio Duncan', 'Quaerat quisquam quaerat ipsum porro aliquam dolor.', 4, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dexter Ford', 'Ipsum modi non sit non modi modi neque.', 5, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Kamal', 'Quaerat labore sit magnam quaerat eius.', 10, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Paul Desjardins', 'Dolor velit amet est sed amet labore.', 4, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marcus Sparks', 'Aliquam consectetur adipisci sed dolor velit.', 4, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Armand Smith', 'Numquam voluptatem consectetur ut neque neque.', 5, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lucy Smith', 'Amet etincidunt eius sit dolor.', 3, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charles Nosek', 'Aliquam modi est est ipsum.', 6, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Walter Gibson', 'Aliquam sed neque modi.', 7, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nora Kline', 'Aliquam aliquam ipsum dolor quisquam adipisci quiquia ipsum.', 6, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tyler Adair', 'Dolorem sed amet quiquia quisquam dolorem.', 7, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Edward Carmichael', 'Non sit magnam quisquam neque dolor quisquam.', 2, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Adrian Freeman', 'Consectetur consectetur labore adipisci quisquam.', 7, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Shandra Mckenzie', 'Aliquam dolore adipisci quiquia sit etincidunt.', 9, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lydia Moore', 'Aliquam quaerat aliquam aliquam labore est est.', 7, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Debra Dole', 'Voluptatem ut magnam magnam quisquam quiquia.', 5, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Felecia Silva', 'Tempora tempora tempora labore dolorem.', 8, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Gillikin', 'Est aliquam consectetur labore adipisci ipsum eius ut.', 9, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Victor Klingbeil', 'Ipsum porro neque ut adipisci.', 5, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sarah Vidal', 'Dolorem eius ipsum ipsum aliquam tempora dolor.', 7, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Denise White', 'Etincidunt porro modi eius dolore non tempora.', 8, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Phillip Perryman', 'Ut ipsum dolor ipsum tempora sit porro quisquam.', 7, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Renay Moreno', 'Voluptatem tempora dolor dolore.', 10, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Shonta Holmes', 'Modi ipsum sed ut ut labore consectetur.', 3, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Vesta Waters', 'Labore numquam porro quisquam velit quaerat quaerat sit.', 1, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cheryl Rice', 'Est quiquia ut consectetur labore.', 4, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kiera Laramore', 'Labore labore sit tempora dolore etincidunt neque.', 7, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rosemary Moore', 'Quiquia porro amet adipisci.', 2, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lilly Schuler', 'Amet consectetur etincidunt non sit numquam magnam dolore.', 4, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Helen Jones', 'Consectetur eius amet magnam non quiquia magnam.', 1, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Patrick Sexton', 'Ipsum consectetur adipisci consectetur aliquam dolor.', 10, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nidia Winfield', 'Numquam neque quisquam consectetur dolorem sit.', 4, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ora Kovar', 'Quiquia modi aliquam velit.', 2, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kenyetta Reynolds', 'Eius dolore magnam est modi.', 2, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tracey Berglund', 'Quisquam numquam ipsum dolor modi etincidunt.', 4, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Hope Peterson', 'Adipisci quaerat voluptatem dolor consectetur ipsum sit dolore.', 6, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Hisaw', 'Modi quiquia non sit est.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Warren Anglin', 'Sit dolorem modi tempora etincidunt sed.', 8, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Donald Meece', 'Aliquam ipsum amet neque modi.', 10, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Pilla', 'Magnam porro magnam ut sed ipsum.', 1, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lucy Walker', 'Dolor voluptatem sed ipsum.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Terry Tibbs', 'Neque tempora est dolor neque ipsum numquam.', 5, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Martinez', 'Amet non magnam quaerat adipisci eius.', 8, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bessie Darwin', 'Eius ut etincidunt aliquam.', 2, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jerry Perkins', 'Consectetur dolore quiquia modi neque.', 6, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Anna Reper', 'Adipisci amet velit ut ut adipisci adipisci velit.', 9, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brittany Roger', 'Magnam sed dolor non magnam.', 6, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Martha Spradling', 'Consectetur dolor tempora dolorem ut etincidunt est dolor.', 8, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Fatima Harmon', 'Dolorem dolorem labore dolorem.', 7, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gertrude Hudgens', 'Etincidunt non quiquia quisquam.', 7, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brendon Scofield', 'Adipisci labore ut quaerat dolore sed quiquia dolor.', 4, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maryanne Flowers', 'Aliquam modi quiquia consectetur aliquam tempora.', 2, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cesar Ryan', 'Sit sed quaerat voluptatem quiquia non ut dolorem.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marianna Wood', 'Amet non non dolorem sit.', 1, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Rios', 'Aliquam porro magnam tempora quiquia tempora.', 10, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gayle King', 'Porro adipisci non ipsum.', 5, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Howard Woodall', 'Dolor consectetur voluptatem sed tempora labore tempora magnam.', 3, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marc Scharmer', 'Ipsum quiquia neque aliquam velit.', 9, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Corey Kowalik', 'Quaerat sed sit eius quiquia dolor numquam.', 7, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Anna Stephens', 'Sit tempora consectetur porro quiquia consectetur ipsum.', 10, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ginger Collins', 'Neque consectetur est amet tempora adipisci non.', 1, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jewel Bradshaw', 'Eius velit est quaerat sit amet.', 1, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Christine Michael', 'Tempora adipisci etincidunt porro aliquam etincidunt.', 8, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jamie Mccormick', 'Magnam dolorem voluptatem ut aliquam porro.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Nuss', 'Consectetur labore dolore neque aliquam.', 6, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Albert Swan', 'Magnam sit ut adipisci est.', 7, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Marmo', 'Magnam voluptatem magnam dolore modi.', 9, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Deborah Tusa', 'Eius quiquia porro ut.', 5, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Otis Betts', 'Est quisquam ut dolore.', 9, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('William Willy', 'Non ipsum labore est velit eius quisquam.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bruce Nelson', 'Porro magnam magnam labore numquam.', 4, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charlotte Jones', 'Quiquia quaerat modi est dolore.', 9, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gerald Pichette', 'Amet aliquam amet quisquam quaerat aliquam.', 8, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Geri Kuehnert', 'Ut ipsum dolore numquam aliquam.', 5, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Victoria Marshall', 'Porro numquam consectetur ut neque velit sed.', 8, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sandra Johnson', 'Numquam ut voluptatem velit amet amet sit.', 8, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ronald Todd', 'Quisquam porro magnam dolor.', 5, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Murray', 'Sit amet modi dolore sed velit neque.', 8, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Regina Rhodes', 'Ipsum est tempora neque labore magnam est modi.', 2, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charles Hildreth', 'Ut quaerat neque dolorem velit sed.', 3, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Herbert Smith', 'Sit labore ut modi consectetur dolore voluptatem.', 6, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Megan Fernandez', 'Quaerat adipisci dolor porro aliquam.', 5, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Roberto Balling', 'Numquam labore porro voluptatem numquam ut sit adipisci.', 1, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Linda Brown', 'Sit porro numquam non consectetur amet non labore.', 2, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lester Arsenault', 'Dolorem velit porro modi.', 8, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sara Johnson', 'Dolor sed aliquam quiquia ut eius velit dolore.', 7, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Vince Dulany', 'Quaerat ut porro dolorem.', 4, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julienne Wilczynski', 'Quisquam magnam dolorem quiquia dolore numquam.', 9, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dale Albright', 'Etincidunt ut est tempora.', 3, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rebecca Rettig', 'Tempora quaerat modi velit labore numquam neque dolor.', 1, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Andrew Niebuhr', 'Amet sed magnam adipisci.', 4, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Clayton Fontaine', 'Tempora neque magnam amet.', 1, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brian Webb', 'Magnam labore sed tempora quiquia velit ipsum.', 7, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Margaret Owens', 'Dolorem sit porro labore dolore sit.', 8, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('George Moreno', 'Quaerat est est aliquam ipsum etincidunt.', 1, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brenda Tucker', 'Adipisci amet voluptatem adipisci tempora eius etincidunt ut.', 8, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elisa Szymczak', 'Aliquam porro aliquam ipsum etincidunt.', 3, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Pam Grimsley', 'Est quaerat ut numquam quiquia amet voluptatem tempora.', 6, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nanette Vaughn', 'Sit magnam neque etincidunt sed.', 9, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Walter Henry', 'Adipisci porro quaerat etincidunt.', 5, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Jones', 'Velit sit magnam eius quaerat modi.', 9, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Fred Wakefield', 'Ipsum ipsum dolor consectetur sed.', 5, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sandra Stroupe', 'Dolorem etincidunt consectetur numquam sit voluptatem.', 2, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Linda Sills', 'Quisquam adipisci ipsum consectetur quiquia quiquia velit etincidunt.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sharon Kwon', 'Sit neque quiquia dolorem quiquia non.', 9, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jess Hall', 'Dolorem quaerat voluptatem sit porro ut labore.', 3, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Benjamin Yaiva', 'Neque labore ut etincidunt numquam amet.', 10, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Melanie Tovey', 'Adipisci porro dolorem quaerat aliquam.', 10, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Trent', 'Velit tempora numquam consectetur ipsum modi porro porro.', 4, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Amy Davis', 'Ut ut velit adipisci modi quisquam voluptatem.', 1, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('George Henry', 'Ipsum tempora dolor ipsum velit sit est.', 6, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('George Dubill', 'Quaerat magnam modi ut.', 3, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joanne Stanfield', 'Quiquia etincidunt etincidunt est adipisci modi.', 4, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Juanita Timmons', 'Sed est quiquia quaerat voluptatem ipsum.', 6, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Gladney', 'Voluptatem dolor non est consectetur dolor aliquam quiquia.', 9, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bethany Cole', 'Eius etincidunt non labore.', 4, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Powers', 'Amet sit dolorem labore tempora non.', 6, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Liza Brown', 'Eius dolor numquam est tempora numquam numquam.', 10, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joan Reed', 'Adipisci aliquam labore amet est.', 4, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Patricia Sweet', 'Quaerat quisquam sit numquam consectetur porro.', 3, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Stephanie Montague', 'Consectetur sit amet modi sed numquam.', 1, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lorraine Hillard', 'Velit amet voluptatem sit sit adipisci porro magnam.', 7, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jamie Roberts', 'Aliquam magnam ipsum amet ipsum.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dan Kelly', 'Dolore voluptatem consectetur numquam.', 6, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cherelle Young', 'Velit consectetur consectetur tempora.', 5, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bennett Bennett', 'Quaerat dolorem neque dolore non dolore.', 5, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Debbie Cope', 'Adipisci amet dolor etincidunt aliquam adipisci.', 3, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gloria Hoffman', 'Consectetur neque etincidunt dolor quaerat.', 7, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nancy Green', 'Non ut sed voluptatem tempora quaerat voluptatem.', 10, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ramona Guarnieri', 'Magnam tempora aliquam sed sed ipsum numquam.', 1, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Minnick', 'Dolorem adipisci numquam magnam etincidunt dolor amet.', 3, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lester Sansburn', 'Tempora numquam numquam quaerat amet quaerat est eius.', 9, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Gibson', 'Dolor est sed amet.', 7, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Doreen Chamberlain', 'Neque numquam adipisci numquam aliquam modi dolore.', 1, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jaime Harrison', 'Numquam sit labore dolor magnam sed ut sed.', 10, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Reed', 'Neque adipisci magnam porro quisquam.', 8, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Allen Gresham', 'Magnam velit ipsum sit eius dolor.', 9, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jessica Johnson', 'Magnam porro labore etincidunt quisquam tempora dolor est.', 6, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janis Atkins', 'Tempora adipisci aliquam ipsum labore sit dolorem.', 8, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Valerie Stubbendeck', 'Consectetur voluptatem dolorem adipisci tempora voluptatem adipisci.', 4, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Campbell', 'Dolor quiquia ut numquam.', 9, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Raap', 'Dolore magnam numquam dolor.', 6, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Garrett Ulloa', 'Velit ut sed neque ut tempora eius quaerat.', 4, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Karen Reynolds', 'Dolore ipsum quisquam labore dolor.', 9, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tom Wake', 'Etincidunt non dolorem consectetur.', 5, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joseph Nettles', 'Etincidunt dolore sit velit eius.', 4, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elizabeth Hernandez', 'Sit neque est quisquam.', 8, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Linda Sherer', 'Quiquia labore labore quisquam neque voluptatem.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joseph Knox', 'Dolorem magnam quisquam tempora dolorem.', 2, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Adrian Stillwell', 'Est voluptatem quisquam non.', 4, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carmen Bahr', 'Ut quisquam numquam voluptatem.', 7, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Clarence Landrum', 'Numquam consectetur tempora amet adipisci est tempora.', 10, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elsie Neller', 'Adipisci quiquia quaerat ipsum quisquam est voluptatem non.', 4, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janina Beasley', 'Consectetur quaerat adipisci quisquam ut dolor sit.', 1, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robin Fulton', 'Porro magnam non numquam.', 5, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Laura Vance', 'Est non eius sit etincidunt magnam modi non.', 7, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Wright', 'Dolorem sed amet porro sit dolore aliquam.', 6, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Orpha Payne', 'Aliquam ipsum eius ipsum sed porro magnam.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeffery Epp', 'Modi dolore voluptatem aliquam tempora.', 9, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sarah Replogle', 'Non non tempora neque dolorem ut quiquia dolorem.', 2, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rita Murray', 'Ipsum velit tempora dolor numquam dolor eius.', 9, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joann Sanchez', 'Neque modi etincidunt ipsum amet.', 4, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Ramos', 'Modi tempora quisquam adipisci voluptatem amet.', 5, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Philip Hayes', 'Est consectetur consectetur ipsum dolor porro etincidunt.', 2, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steve Reid', 'Tempora sit quiquia numquam.', 3, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ronald Ware', 'Velit neque tempora tempora.', 3, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Arthur Bowlin', 'Neque voluptatem quisquam numquam numquam dolore velit dolor.', 2, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathleen Stapleton', 'Magnam porro aliquam numquam magnam.', 2, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rosa Strapp', 'Est amet dolor aliquam tempora sed non.', 8, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dwayne Perkins', 'Est porro ipsum quiquia sit adipisci.', 4, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Mahoney', 'Non eius etincidunt dolorem.', 6, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tom Merrett', 'Etincidunt velit modi voluptatem dolore sed non.', 7, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charles Schneider', 'Velit labore quisquam magnam non consectetur sed.', 10, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Harold Williamson', 'Est ut voluptatem quiquia.', 2, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Eric Wilson', 'Magnam eius non quiquia eius numquam quisquam est.', 3, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Anne Grubb', 'Dolore quisquam ipsum sed non.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charles Haynes', 'Labore modi ut labore.', 10, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ruth Thurman', 'Quiquia modi est adipisci porro consectetur porro dolore.', 8, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Lajaunie', 'Est consectetur sed tempora etincidunt.', 4, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joel Murphy', 'Quaerat dolor neque magnam sed etincidunt.', 3, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Angie Deharo', 'Sed tempora numquam sit etincidunt dolor quisquam.', 7, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ida Berringer', 'Ut porro dolor modi neque quiquia.', 10, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathy Ryan', 'Velit quisquam sed quaerat voluptatem velit.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Anne Senske', 'Quiquia non quisquam magnam.', 4, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Calvert', 'Dolorem tempora dolore adipisci sed eius aliquam.', 7, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Thomas White', 'Numquam sed quisquam aliquam neque labore magnam.', 10, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Clark', 'Ut ut tempora dolore consectetur.', 2, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leon Eckard', 'Voluptatem ut eius velit.', 3, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Thomas Mcneil', 'Dolore aliquam ut quaerat quisquam.', 1, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leslie Donart', 'Sit tempora sit non consectetur.', 4, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Phyllis Anglin', 'Magnam modi etincidunt modi dolor sed ipsum dolorem.', 9, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leonard Walker', 'Sit non quiquia velit.', 4, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Fermina Legrand', 'Amet dolor tempora quiquia est.', 4, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Esperanza Hawkins', 'Ut consectetur velit quaerat est quiquia numquam magnam.', 5, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Patricia Vale', 'Est magnam quaerat eius voluptatem neque est labore.', 4, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Pluemer', 'Dolor tempora sit tempora quaerat dolore.', 3, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Fulton', 'Amet labore tempora sed dolorem dolore etincidunt tempora.', 5, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Monroe', 'Sit consectetur sed neque quaerat consectetur porro neque.', 4, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mike Jackson', 'Ipsum quaerat non voluptatem tempora neque.', 8, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Dunn', 'Est labore etincidunt sed dolorem est.', 6, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Bridges', 'Quisquam adipisci est amet labore.', 3, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Paulette Anderson', 'Neque quaerat consectetur modi numquam quisquam neque porro.', 7, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marie Bulloch', 'Tempora dolor quaerat ut quiquia consectetur quiquia.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Silago', 'Sed aliquam labore non sed dolor.', 5, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Terry Simonson', 'Magnam magnam modi etincidunt amet ipsum neque.', 1, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julia Reinhardt', 'Eius ut labore aliquam non magnam non.', 2, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Melissa Hepner', 'Dolor porro labore dolore.', 5, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Beatrice Baxter', 'Dolore adipisci neque quisquam dolore.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rebecca Wingo', 'Ut dolorem consectetur etincidunt quisquam tempora labore.', 7, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Amber Coviello', 'Eius aliquam sed tempora.', 10, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Christopher Moreno', 'Modi etincidunt quiquia dolore.', 9, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Timothy Wang', 'Eius quiquia quiquia velit velit.', 10, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Frank Roberts', 'Quisquam adipisci porro consectetur neque labore.', 8, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Becker', 'Sed ut non aliquam velit quaerat.', 7, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janice Schafer', 'Magnam adipisci tempora dolore etincidunt modi numquam sed.', 3, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julia Reyes', 'Aliquam quisquam consectetur quaerat non.', 5, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leroy Gray', 'Eius magnam labore sed porro non voluptatem.', 7, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Connie Michaels', 'Amet voluptatem aliquam porro tempora velit.', 4, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janice Collins', 'Eius consectetur aliquam adipisci.', 1, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ben Baker', 'Est neque amet eius amet adipisci.', 5, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Raymond Sweney', 'Etincidunt quisquam eius consectetur voluptatem quisquam.', 4, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Helen Bader', 'Sed sed dolore est sit consectetur voluptatem numquam.', 2, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Whitlock', 'Quaerat dolor consectetur numquam neque labore.', 2, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Douglas Greenman', 'Non etincidunt ut voluptatem non.', 5, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Libby Gross', 'Modi est porro ut.', 2, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Alex Mcdowell', 'Quiquia tempora non etincidunt quisquam.', 8, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julia Whitley', 'Porro quisquam quisquam modi ipsum.', 9, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Frank Martin', 'Sit ut numquam non velit velit.', 9, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Claudette Duncan', 'Non non consectetur modi.', 9, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julio Smith', 'Velit quaerat dolore consectetur porro modi neque.', 7, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steven Bell', 'Magnam amet voluptatem ut non est neque.', 4, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Chad Knop', 'Tempora amet magnam adipisci quisquam voluptatem.', 4, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Jines', 'Modi dolorem aliquam sit dolor ipsum eius magnam.', 9, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Clifton Bayless', 'Etincidunt voluptatem quaerat consectetur quisquam adipisci.', 8, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathleen Walker', 'Quaerat amet ipsum modi ipsum ut porro.', 1, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Billy Holmes', 'Quaerat voluptatem amet consectetur sit adipisci amet ipsum.', 5, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joseph Rayborn', 'Non etincidunt quisquam magnam voluptatem non consectetur consectetur.', 3, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tiffany Earnest', 'Voluptatem eius velit dolore velit.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Manuel Fritz', 'Magnam quiquia labore sed neque non.', 6, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeffrey Kneip', 'Ut sit amet non voluptatem numquam dolor ut.', 10, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carol Thompson', 'Porro velit etincidunt dolore numquam modi quisquam.', 1, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carrie Isley', 'Quisquam ut eius modi eius sed.', 2, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Freda Howard', 'Porro voluptatem eius consectetur aliquam quisquam numquam amet.', 7, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cecilia Roberts', 'Velit sed modi sed amet porro.', 10, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Danny Scott', 'Amet aliquam sit sed quaerat.', 4, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Katherine Jackson', 'Modi aliquam numquam labore est magnam modi porro.', 6, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Billy Spurlin', 'Sed dolor ipsum quiquia aliquam neque modi ut.', 10, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Micah Boldt', 'Quisquam est quiquia est sed amet ut ut.', 8, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bernice Guy', 'Ipsum consectetur aliquam eius dolore est velit dolorem.', 6, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Stevens', 'Quisquam neque ut ipsum.', 1, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Propst', 'Aliquam dolor voluptatem dolore magnam etincidunt sit non.', 8, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Wendy Randolph', 'Non non adipisci consectetur neque quisquam dolore eius.', 3, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elaine Blach', 'Ipsum ut etincidunt eius velit.', 9, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lee Saulsberry', 'Dolorem dolorem porro dolore.', 6, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Denis Jackson', 'Adipisci sit quaerat amet modi dolor sed.', 4, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Esther Davis', 'Labore sed non porro est neque etincidunt numquam.', 9, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Garry Roberts', 'Dolor sit eius porro.', 8, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Virginia Garza', 'Quaerat non adipisci porro modi.', 5, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Darla Baggesen', 'Adipisci magnam voluptatem adipisci quaerat quisquam.', 3, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Zeigler', 'Eius tempora neque ipsum.', 3, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Frances Falk', 'Quiquia etincidunt dolor sit labore dolorem consectetur.', 9, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Vincent Hernandez', 'Voluptatem voluptatem non ut.', 8, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Bienfang', 'Voluptatem dolore aliquam porro tempora.', 8, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Deborah Rutherford', 'Porro adipisci consectetur non dolore dolore.', 1, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marshall Prisco', 'Non modi dolore consectetur dolore tempora.', 8, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jewell Khouri', 'Etincidunt eius quiquia dolorem.', 1, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leslie Cliff', 'Dolore quisquam aliquam labore sit sed tempora etincidunt.', 8, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carrie Russell', 'Porro modi quaerat sit tempora.', 5, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Hartly', 'Voluptatem quaerat non etincidunt labore non tempora quaerat.', 5, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rosemary Ross', 'Ipsum modi etincidunt eius neque dolore.', 2, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Fred Henderson', 'Porro non etincidunt modi voluptatem.', 9, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lisa Theriault', 'Quaerat ipsum etincidunt porro amet quaerat.', 8, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Agatha Harland', 'Labore quisquam etincidunt quaerat est quisquam sit dolore.', 7, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Mchenry', 'Est numquam consectetur amet quaerat non adipisci etincidunt.', 7, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Janette Searcy', 'Amet ut amet quisquam aliquam neque.', 3, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Christine Bearden', 'Ipsum non ut ipsum est ipsum.', 10, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Mohr', 'Modi quisquam est dolorem dolor.', 6, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Paul Summers', 'Quisquam tempora est dolore magnam quaerat.', 9, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Clare Hudnall', 'Quaerat adipisci eius non neque consectetur etincidunt.', 4, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jewel Faulk', 'Etincidunt consectetur velit amet aliquam quiquia.', 7, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Pearl Primm', 'Porro est ipsum eius neque.', 9, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Barbara Mercer', 'Adipisci velit velit etincidunt modi labore modi.', 9, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Srinivasan', 'Consectetur ipsum quiquia neque dolorem quaerat modi quaerat.', 1, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Valerie Boivin', 'Sed quiquia labore dolor dolore amet aliquam.', 6, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Martin', 'Etincidunt velit tempora quiquia modi.', 10, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Susan Hernandez', 'Porro labore est velit neque aliquam.', 2, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Melanie Johnson', 'Quiquia magnam eius numquam velit neque modi neque.', 9, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Eleanor Lanier', 'Neque aliquam modi quaerat.', 8, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bonnie Lamy', 'Eius non quisquam tempora est neque.', 4, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeffrey Register', 'Velit sed labore eius.', 8, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Blanche Smalls', 'Sed ut velit non dolorem dolorem ut.', 4, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Johnson', 'Eius amet quiquia etincidunt ut consectetur eius.', 10, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jack Gonzales', 'Consectetur sit tempora quiquia voluptatem sed adipisci non.', 3, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Peter Canty', 'Quiquia neque quisquam aliquam modi sit.', 1, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Diane Saenz', 'Velit consectetur numquam etincidunt voluptatem modi quiquia.', 6, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Perdue', 'Dolor aliquam neque dolore non aliquam eius.', 3, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Heather Shirk', 'Labore dolor dolor quaerat porro porro ipsum.', 7, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Stacy Calvary', 'Voluptatem labore eius velit quisquam.', 6, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Acosta', 'Ipsum magnam adipisci etincidunt eius quaerat labore voluptatem.', 2, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Todd Little', 'Magnam sit ipsum adipisci numquam.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Margie Angeles', 'Neque tempora non quaerat quisquam sed.', 2, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steve Sawyer', 'Etincidunt ut quaerat quisquam etincidunt voluptatem.', 4, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Benjamin Albert', 'Magnam adipisci quaerat dolor.', 4, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lana Munoz', 'Quiquia tempora neque consectetur ut.', 2, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Kyle', 'Non sit neque dolor quaerat dolorem sed.', 5, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bobby Sylvia', 'Porro quiquia amet magnam.', 3, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ofelia Girman', 'Quisquam quaerat labore adipisci ut est magnam.', 8, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Melissa Dixon', 'Quaerat non dolore est magnam porro magnam eius.', 8, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jesus Carriere', 'Porro non aliquam est etincidunt modi.', 2, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Roberta Defir', 'Neque dolor eius consectetur.', 2, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Darling', 'Modi ipsum consectetur sed ipsum quisquam consectetur dolor.', 8, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Numbers', 'Est eius labore numquam quaerat.', 5, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gary Chavira', 'Sed neque consectetur aliquam ipsum velit amet.', 2, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Donald Dillingham', 'Quiquia sed ut dolore tempora quiquia.', 8, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Luann Gibbs', 'Est adipisci porro ut.', 10, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lewis Holm', 'Porro velit voluptatem dolore dolore adipisci quiquia.', 7, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Becton', 'Dolor non quiquia modi adipisci neque est dolor.', 8, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dustin Bedward', 'Quisquam non amet etincidunt voluptatem non.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Clinton Jackson', 'Amet non labore quiquia eius consectetur.', 10, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Roscoe Davis', 'Voluptatem aliquam neque labore numquam ipsum.', 3, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Joshua Scott', 'Sit ut tempora numquam ipsum.', 7, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Abigail Quezada', 'Eius labore numquam modi aliquam.', 3, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Monfort', 'Etincidunt ut voluptatem consectetur labore.', 5, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nicki Harvey', 'Sit modi magnam ut.', 9, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Andrew Rodgers', 'Voluptatem eius aliquam voluptatem quiquia ipsum.', 6, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nancy Guillory', 'Sed non quaerat porro dolore.', 3, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Silvey', 'Dolor numquam modi modi quiquia tempora amet ipsum.', 5, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rachel Moore', 'Porro non ipsum non numquam numquam porro.', 3, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Douglas Strickland', 'Adipisci amet porro dolor sed labore dolor labore.', 3, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Pete Humphries', 'Etincidunt non amet ut ipsum voluptatem aliquam.', 5, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Henrietta Hill', 'Ipsum numquam est eius.', 7, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cynthia Ring', 'Dolore sed neque neque.', 8, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marie Fisher', 'Labore quisquam neque consectetur ut.', 9, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Linda Rone', 'Ipsum tempora voluptatem numquam velit amet.', 10, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jane Hall', 'Consectetur ipsum etincidunt porro porro consectetur adipisci.', 2, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Faith Tippens', 'Porro sit aliquam consectetur modi eius.', 3, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Schuette', 'Etincidunt adipisci labore velit consectetur aliquam adipisci sed.', 5, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lashanda Rios', 'Porro est adipisci dolor.', 10, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gretchen Caldwell', 'Amet porro dolore ipsum.', 2, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Johnny Burton', 'Voluptatem adipisci eius non dolorem dolore porro numquam.', 2, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Santiago', 'Numquam magnam quaerat tempora quiquia ipsum magnam velit.', 3, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lynn Groce', 'Dolorem etincidunt ut sed.', 4, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Douglas Jackson', 'Sit dolor consectetur aliquam.', 3, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mauro Mccalmont', 'Adipisci tempora aliquam eius sed est ipsum.', 10, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Walter Pridgen', 'Sed voluptatem sed sit porro adipisci.', 3, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('William Vue', 'Quaerat labore numquam etincidunt eius amet velit.', 2, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gustavo Mcginnis', 'Consectetur ipsum magnam quaerat.', 7, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jerry Isbrecht', 'Ipsum consectetur eius eius.', 7, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Eric Sampieri', 'Etincidunt sit quisquam ut aliquam ipsum etincidunt tempora.', 5, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lee Vereen', 'Dolor quisquam non dolore dolore dolorem numquam tempora.', 5, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Rosemary Jaramillo', 'Dolore labore dolore sit sed sed etincidunt non.', 5, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Randall Pitts', 'Etincidunt ut dolore amet tempora sed.', 10, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kevin Bowers', 'Labore dolore velit quaerat porro amet.', 5, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Claire Estrada', 'Adipisci amet dolor modi.', 3, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Larry Washington', 'Quaerat sit voluptatem etincidunt consectetur.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Theresa Tuttle', 'Neque ipsum tempora porro velit numquam.', 7, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathy Coughlin', 'Aliquam consectetur neque magnam quisquam non.', 7, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Gomez', 'Magnam consectetur ut dolore dolorem aliquam sed dolor.', 2, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Arnold Blankenship', 'Voluptatem labore eius dolor sed quisquam sed.', 4, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ida Pullen', 'Quiquia est est ut voluptatem dolor ut.', 2, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lynne Roudabush', 'Tempora adipisci neque eius.', 3, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dorothy Howell', 'Neque adipisci velit numquam voluptatem.', 5, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Alice Rollo', 'Non ipsum neque tempora ipsum ut neque.', 10, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Anthony Miller', 'Consectetur adipisci porro numquam voluptatem non ut ut.', 1, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Terry Flatley', 'Consectetur aliquam ut consectetur dolorem.', 5, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Martha Ruffin', 'Aliquam amet tempora aliquam dolorem sit velit.', 7, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lewis Ewing', 'Tempora etincidunt sed labore.', 6, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Klara Richards', 'Dolor velit est velit adipisci.', 9, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jaclyn Garcia', 'Numquam dolor magnam ut ipsum dolore.', 4, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sondra Orellana', 'Numquam adipisci est tempora.', 9, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Marsha Short', 'Porro labore adipisci etincidunt adipisci consectetur numquam.', 2, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maria Cranmer', 'Labore voluptatem est est etincidunt quisquam consectetur.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Ruble', 'Ipsum modi dolorem amet magnam neque tempora amet.', 6, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jenifer Lichtenberg', 'Dolore numquam neque adipisci.', 9, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Timothy Oneill', 'Adipisci amet sit quiquia non.', 8, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Julia Green', 'Quisquam aliquam est amet quiquia quiquia.', 2, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Karen Rodriguez', 'Quaerat tempora modi velit.', 6, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Roxy Cothran', 'Ut non eius sed.', 7, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Paul Smith', 'Consectetur labore aliquam dolor.', 5, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Pope', 'Voluptatem modi etincidunt etincidunt.', 5, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elizabeth Polson', 'Etincidunt neque ut sed.', 3, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Basil Bryan', 'Amet neque sit modi porro dolor quaerat est.', 5, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Bien', 'Velit eius ut voluptatem non sit.', 1, 5);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Frazier', 'Labore consectetur tempora numquam amet.', 6, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Reynaldo White', 'Etincidunt magnam numquam ipsum quaerat.', 6, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brenda Cline', 'Aliquam adipisci velit sit sit.', 3, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ruth Montello', 'Velit quaerat aliquam aliquam numquam sit consectetur consectetur.', 4, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathleen Douglass', 'Quaerat porro adipisci non tempora.', 8, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Dan Peters', 'Voluptatem dolore sed modi.', 6, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Sexton', 'Quisquam est amet amet.', 2, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nancy Heinemann', 'Labore consectetur amet adipisci.', 4, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Thompson', 'Sit velit consectetur magnam porro quisquam.', 6, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Nichole Robinson', 'Quiquia neque numquam quaerat neque.', 1, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sean Minton', 'Dolor tempora eius sed etincidunt.', 7, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Levi Fenton', 'Voluptatem labore neque est dolor.', 6, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Susan Little', 'Amet dolore amet quisquam.', 7, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Yvonne Giles', 'Porro quaerat eius sit aliquam.', 9, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Curtis Gutierrez', 'Sit modi ut est dolore.', 5, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Blanco', 'Numquam labore sit labore modi neque.', 10, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Hazel Woods', 'Dolore neque magnam non.', 4, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steve Walquist', 'Sit eius dolor neque porro ipsum adipisci voluptatem.', 9, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Craig Baker', 'Quisquam labore modi dolor consectetur aliquam adipisci dolorem.', 9, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Patrick Jackson', 'Amet porro ipsum velit aliquam tempora eius.', 9, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ashley Murray', 'Ut sit consectetur ut aliquam est quiquia quiquia.', 4, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jefferey Reed', 'Quiquia sed dolor eius porro dolorem ipsum.', 3, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Mccay', 'Ut amet dolor dolorem non modi.', 5, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tina Harding', 'Sed amet neque adipisci magnam dolore sed quaerat.', 1, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kendall Tucker', 'Numquam quaerat magnam quaerat eius etincidunt labore labore.', 3, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeanne Sampson', 'Etincidunt neque voluptatem tempora adipisci quiquia.', 3, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Martin', 'Dolore non quisquam quisquam.', 9, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jo Schneeman', 'Non non aliquam quaerat numquam voluptatem.', 8, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bryan Bishop', 'Quiquia dolore sit dolor.', 9, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Edgar Shotwell', 'Dolore non sed sed neque consectetur.', 9, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Acree', 'Eius quaerat dolorem quaerat amet magnam sed dolore.', 10, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kirk Hearnen', 'Amet porro amet amet.', 3, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Erin Odaniel', 'Etincidunt modi velit amet quaerat.', 3, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Bradley Mellish', 'Consectetur modi sed est dolorem.', 5, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carlos Mcdaniel', 'Quiquia est aliquam porro magnam etincidunt sed est.', 8, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Deyoung', 'Neque numquam neque quisquam.', 8, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Tritz', 'Sed sed sed eius neque ipsum quiquia.', 7, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('William Johnson', 'Modi consectetur dolor labore magnam.', 1, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steve Chaney', 'Quaerat sit eius dolor etincidunt voluptatem voluptatem dolorem.', 7, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lucy Ungar', 'Tempora sit adipisci porro sed sed.', 3, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Randall Riley', 'Neque neque porro non consectetur neque quiquia.', 5, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('John Veilleux', 'Numquam ut tempora amet.', 7, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Charlie Kasper', 'Dolore magnam eius tempora dolorem ipsum non porro.', 10, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Derek Dumas', 'Porro est quisquam porro ut dolorem dolorem dolorem.', 2, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Raymond Weaver', 'Tempora tempora dolor numquam sit amet.', 6, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Elizabeth Jablonski', 'Ipsum non numquam non quiquia quiquia voluptatem tempora.', 7, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gretta Hall', 'Consectetur non porro ut quiquia.', 6, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Gene Maas', 'Sed voluptatem labore magnam dolore.', 2, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Cynthia Gonzalez', 'Labore dolore modi quaerat magnam consectetur est.', 6, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Paul Soto', 'Sed dolore dolor labore.', 5, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Williams', 'Magnam quisquam est aliquam dolorem.', 5, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Fred Andrade', 'Numquam quisquam velit amet.', 9, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Deborah Conner', 'Est tempora sit sed.', 2, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Brenda Chacon', 'Amet adipisci numquam magnam sit etincidunt.', 5, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Steven Demarais', 'Ut magnam quiquia sed.', 3, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Reva Stewart', 'Dolorem ut ipsum adipisci dolor ipsum.', 8, 23);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Slowinski', 'Eius ut velit quaerat non quisquam quaerat dolor.', 2, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ashley Adams', 'Aliquam non modi velit amet.', 3, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jeanine Askew', 'Amet quiquia dolor quisquam sit modi.', 6, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Eugene Goldberg', 'Voluptatem modi numquam dolore porro neque porro.', 4, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jacqueline Blaise', 'Labore numquam magnam sit magnam.', 2, 12);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tonya Rosario', 'Voluptatem tempora modi magnam tempora velit consectetur labore.', 1, 19);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Peter Shuster', 'Velit adipisci quaerat sed.', 3, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Tooms', 'Porro numquam labore ipsum etincidunt ut dolore.', 6, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Mary Sanders', 'Etincidunt sed dolore porro.', 3, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Kathleen Bullock', 'Ipsum numquam dolore ut.', 10, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ryan Jackman', 'Consectetur aliquam dolorem velit voluptatem.', 1, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Carol Moton', 'Dolore tempora numquam non dolore consectetur.', 7, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Lelia Trammell', 'Numquam quisquam est numquam tempora.', 10, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michelle Martin', 'Dolore adipisci ipsum modi.', 10, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Sheila Well', 'Neque aliquam voluptatem tempora amet magnam eius consectetur.', 8, 3);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Leslie Welty', 'Labore labore voluptatem voluptatem quisquam velit aliquam porro.', 4, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Karen Williams', 'Etincidunt quaerat dolorem velit neque amet labore.', 6, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Louis Pitts', 'Numquam ipsum dolore dolore consectetur quaerat ipsum dolor.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('James Rivera', 'Etincidunt dolorem ipsum quaerat etincidunt ipsum non non.', 10, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('David Burns', 'Ut voluptatem dolore amet magnam dolorem adipisci.', 1, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jessica Moses', 'Aliquam sed labore voluptatem aliquam tempora.', 3, 16);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Neil Mclaughlin', 'Modi ipsum numquam amet amet dolor neque neque.', 8, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Meredith Bowen', 'Quaerat quisquam neque velit amet ut non.', 5, 9);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Tiffany Dennis', 'Numquam consectetur ut sit.', 4, 22);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Virginia Davis', 'Ipsum dolor est amet quisquam labore adipisci.', 2, 1);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jacob Fong', 'Porro sit labore quiquia ut.', 2, 21);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Deidre Cockrell', 'Est modi porro non ut porro modi.', 8, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Justin Corn', 'Sit labore voluptatem labore.', 6, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Walter Sanders', 'Amet sit porro quiquia dolor non velit magnam.', 9, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Horace Messler', 'Labore velit ut voluptatem porro neque voluptatem porro.', 4, 6);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Deneen Mcrae', 'Ut magnam velit sit sed.', 8, 7);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Christopher Washington', 'Porro etincidunt modi dolorem adipisci.', 8, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Richard Moss', 'Etincidunt numquam dolore dolore dolor.', 7, 15);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Florence Tannehill', 'Quisquam quisquam porro non adipisci sed ut sed.', 6, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Willie Hogan', 'Dolor sed aliquam adipisci ipsum dolorem.', 1, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Pauline Lumpkins', 'Dolorem etincidunt aliquam ipsum porro modi eius.', 8, 4);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Samantha Kennedy', 'Numquam amet modi porro sed voluptatem numquam.', 1, 10);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Beth Carrillo', 'Dolor est non non dolore ut.', 9, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Russell Surina', 'Consectetur sed non ut sed.', 9, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Ted Green', 'Numquam eius dolore neque sit eius etincidunt magnam.', 5, 13);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('George Mcguigan', 'Dolore est non quiquia porro eius dolore.', 9, 17);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Jonathan Bjorseth', 'Sed eius amet consectetur amet magnam consectetur voluptatem.', 1, 18);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Debra Roby', 'Dolor eius neque porro porro etincidunt dolore.', 6, 8);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Maureen Wampler', 'Aliquam modi dolorem ipsum consectetur dolor.', 4, 2);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Homer Sullivan', 'Labore amet est quisquam est.', 8, 14);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Robert Lawson', 'Quaerat ut modi aliquam neque quisquam neque aliquam.', 8, 20);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Michael Smithheart', 'Non etincidunt magnam etincidunt.', 8, 11);
INSERT INTO feedback (name, jhi_comment, rating, place_id) VALUES ('Thomas Shakir', 'Sit dolore voluptatem tempora.', 2, 16);
