INSERT INTO place (name, address, jhi_type) VALUES ('Vapiano Solaris', 'Estonia puiestee 9, 10143 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('McDonald''s', 'Mahtra 29, 13811 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Katusekohvik', 'Viru 13/15, 10140 Tallinn', 'CAFE');
INSERT INTO place (name, address, jhi_type) VALUES ('St. Patrick''s, Pirita', 'Merivälja tee 5, 11911 Tallinn', 'PUB');
INSERT INTO place (name, address, jhi_type) VALUES ('Tommi Grill', 'Tatari 64, 10134 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Meat Market Steak & Cocktail', 'Küütri 3, 51007 Tartu', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Kohvik Werner', 'Ülikooli 11, 51003 Tartu', 'CAFE');
INSERT INTO place (name, address, jhi_type) VALUES ('Gustav Gastro Cafe', 'Riia 1, 51004 Tartu', 'CAFE');
INSERT INTO place (name, address, jhi_type) VALUES ('Ristiisa Pubi', 'Küüni 7, 50104 Tartu', 'PUB');
INSERT INTO place (name, address, jhi_type) VALUES ('Entri Restoran ja Catering', 'Küüni 7, 51007 Tartu', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Cookbook', 'Turu 2, 51014 Tartu', 'CAFE');
INSERT INTO place (name, address, jhi_type) VALUES ('Steffani Pizzarestoran', 'Nikolai 24, Pärnu, 80011 Pärnu maakond', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Jahtklubi Restoran', 'Lootsi 6, Pärnu, 80012 Pärnu maakond', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Mahedik - kohvik ökogurmaanile', 'Pühavaimu 20, Pärnu, 80011 Pärnu maakond', 'CAFE');
INSERT INTO place (name, address, jhi_type) VALUES ('Burger Box', 'Kopli 4a, 10412 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Diner', 'Vabaduse puiestee 39, 11212 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Diner Pärnu', 'Riia maantee 110a, Pärnu, 80042 Pärnu maakond', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Sushi Panda Kesklinn', 'Narva maantee 2, 10117 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Vana Villemi Pubi', 'Tartu maantee 50, 10115 Tallinn', 'PUB');
INSERT INTO place (name, address, jhi_type) VALUES ('Hell Hunt', 'Pikk 39, 10133 Tallinn', 'PUB');
INSERT INTO place (name, address, jhi_type) VALUES ('Da Vinci Pasta & Pizza', 'Riia maantee 170, Pärnu, 80025 Pärnu maakond', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Cantina Carramba', 'A. Weizenbergi 20, 10150 Tallinn', 'RESTAURANT');
INSERT INTO place (name, address, jhi_type) VALUES ('Gourmet Coffee', 'L. Koidula 13a, 10150 Tallinn', 'CAFE');
